### ISSUE TITLE
Ctrl+J Being overridden

### ISSUE THREAD

**Issue by joetoth** [tmux-plugins/tmux-copycat#53] opened 2014-10-30 20:14 UTC
In my tmux.conf I have the following to move around panes. Somewhere in this plugin this binding is being reset to default "accept-line". Ctrl+J works until I do something like Ctrl+a, Ctrl+f

bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)g?(view|vim?)(diff)?$' && tmux send-keys C-j) || tmux select-pane -D"

I did a search on this repo for ctrl_j but didn't find anything. Hopefully you can point me in the right direction.

Thanks for making an awesome plugin!

**Comment by bruno-** [comment] 2015-01-02 15:37
Hey,
sorry for the long wait. @vellvisher, yea, you are right - that is related.

And yep, this plugin overrides `bind -n C-j` (as well as `C-c`, `Enter` and `q`) during the copycat mode. After a user exits the copycat mode, those keys are unbound and that unfortunately means your mappings are lost.

These overrides are required so that copycat mode "knows" when to exit. Yes, it's a hack.

This is not documented because I thought no one would ever bind these keys with `-n` flag. And really, maybe it's better not to use `-n` at all, especially given there are plenty of unused keys with `prefix`.

I don't know if that's the solution you want to hear, but if we were talking friendly in person, I'd recommend using another key, ideally also using `prefix`.

If you really, really, want continue using `C-j` then:
 1. list all the mappings in vi-copy mode with this command: `tmux list-keys -t vi-copy`. Verify that `C-j` is bound to `copy-selection`.
 2. unbind `C-j` so that it no longer exits copy mode. This is the line to put in `tmux.conf`: `unbind -t vi-copy C-j`.
 3. restart tmux. Verify that `C-j` is \*no* longer present in the output of `tmux list-keys -t vi-copy`
 4. after this, your `C-j` binding should work properly

Ideally the above helps so I hope you guy's won't mind I close this issue as done as there's been a ton of them opened during the holidays. If something's still bothering you or you have questions feel free to reopen!

**Closed by bruno-** 2015-01-02 15:37 UTC

**Comment by ejoubaud** [comment] 2015-12-03 17:27
Hey there, just wanted to signal I've got the same issue, and I reckon it will be a common one as overloading `C-j` with `-n` is recommended in the readme of the pretty popular `vim-tmux-navigator`: https://github.com/christoomey/vim-tmux-navigator#tmux

I guess a decent share of tmux+vim users use that plugin with that binding. It's really convenient.

`prefix + I` fixes the issue by reloading the tmux conf, but only until the next copycat search, where it messes up `C-j` again.

Your workaround (adding `unbind -t vi-copy C-j` to `.tmux.conf`) does work great however, and solved the problem for me, thanks a lot for that. If the issue is not fixable, it might be worth mentioning in the readme, not sure everyone will find it here. And/or possibly have copycat run the `unbind` by default, or with an option ¯\_(ツ)_/¯

**Comment by bruno-** [comment] 2015-12-14 00:44
Wanna open a PR that adds a note to [this file](https://github.com/tmux-plugins/tmux-copycat/blob/master/docs/limitations.md)?

**Comment by ejoubaud** [comment] 2015-12-14 14:33
Sure: #88
